spring:
  application:
    name: user-center-backend-master
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/userdatabase?useUnicode=true&amp;characterEncoding=utf8&amp;serverTimezone=UTC&amp;useSSL=false
    url: jdbc:mysql://localhost:3306/userdatabase
    username: root
    password: '011216'

  # session 失效时间
  session:
    timeout: 86400
    store-type: redis

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  #redis
  redis:
    port: 6379
    host: localhost
    database: 0

  profiles:
    active: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
        same-site: none
        secure: true